version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: rodriguescb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha01
      MYSQL_DATABASE: rodriguescb
    ports:
    - "3306:3306"
    cap_add:
      - SYS_NICE
